### ISSUE TITLE
SQLite3 adapter

### ISSUE THREAD

**Issue by SkylerLipthay** [SkylerLipthay/schemamama#1]
@cmsd2 Thanks for publishing your SQLite adapter! :smile: I've linked it in this repo's README — let me know if this is a problem. Also let me know if you had any troubles or have any suggestions for improving the library.

**Comment by cmsd2** [comment]
glad to help.

I tried first with rust-sqlite3, but found that since it uses mutable statements and connections that it wasn't compatible - the mut keyword infected everything.

I deviated slightly from your postgres adapter in that I try to preserve Results just a bit longer, instead of panicking. The up and down methods on the migrator trait don't return anything so panic is still the only option eventually, but I wonder what your thoughts are on that.

Oh and finally, schemamama uses some unstable features so it only works on nightly. Any ideas how that will evolve?

**Comment by SkylerLipthay** [comment]
I just quickly reviewed rust-sqlite3 and don't understand why the connection/querying methods must be marked as mutable. Regardless, did you consider utilizing interior mutability (`RefCell`) with rust-sqlite3?

I agree with your design decision to resist panics as much as possible. I was quite lazy with this and didn't understand the ergonomics of Rust errors at the time. My thought was that migrations are one-off jobs supervised by the developer, so panicking was fine. However, I'm going to be using this library to migrate databases at runtime, so granular error handling is a must. I'll be making relevant changes in the coming weeks.

Indeed the library uses nightly features. When I wrote Schemamama at the beginning of the year, I figured all of the these features would magically quickly stabilize. I'll have to review the status of these features and replace them with stable alternatives — my current project will be deployed for 1.3.

Thank you for your feedback!

**Comment by SkylerLipthay** [comment]
@cmsd2 

FYI Schemamama is now stable-friendly (0.0.9) and uses `Result` instead of panicking (0.0.11).

I see you updated the rustqlite adapter a few days ago — sorry for the turbulence! :sob: I'm finally getting around to working on this library again. Let me know if you have any problems with the slightly modified API or if you have any further suggestions. Thanks as always.
